################################################################
## Light / Hue
################################################################

- platform: hue
  host: 192.168.1.211
  allow_unreachable: true
  filename: phue.conf
