################################################################
## Light / LimitlessLED
################################################################

- platform: limitlessled
  bridges:
    - host: !env_var LIMITLESSLED_HOST
      version: 5
      port: 8899
      groups:
      - number: 1
        type: rgbw
        name: Garage
