################################################################
## Light / LimitlessLED
################################################################

- platform: limitlessled
  bridges:
    - host: 192.168.1.16
      version: 5
      port: 8899
      groups:
      - number: 1
        type: rgbw
        name: Garage
