# Restart Homebridge on HASS start
shell_command:
  restart_homebridge: 'sudo su pi -c "pm2 restart homebridge"'
  start_homebridge: 'sudo su pi -c "pm2 start homebridge"'
  stop_homebridge: 'sudo su pi -c "pm2 stop homebridge"'

automation:
  - alias: Restart HomeBridge on Home Assistant Startup
    trigger:
      platform: event
      event_type: homeassistant_start
    action:
      - delay: '00:01:00'
      - service: shell_command.restart_homebridge
