################################################################
## Switch / SmartThings
################################################################

- platform: mqtt
  name: Pepper Fan
  state_topic: smartthings/pepper_fan/switch
  command_topic: smartthings/pepper_fan/switch
  payload_on: 'on'
  payload_off: 'off'
  retain: true
