################################################################
## Group / Views
################################################################

home:
  name: Home
  view: yes
  entities:
    - group.back_porch
    - group.dining_room
    - group.entryway
    - group.friends
    - group.front_porch
    - group.garage
    - group.guest_bedroom
    - group.hallway
    - group.household
    - group.hue_lights
    - group.kitchen
    - group.laundry_room
    - group.living_room
    - group.master_bathroom
    - group.master_bedroom
    - group.master_closet
    - group.scripts

people:
  name: People
  view: yes
  entities:
    - group.person_dale
    - group.person_courtney
    - group.person_jonathan
    - group.person_jon
    - group.person_lyndee
    - group.person_parker
    - group.person_russell
    - group.person_tonyia
    - group.person_tristan

sensors:
  name: Sensors
  view: yes
  entities:
    - group.weather

media:
  name: Media
  view: yes
  entities:
    - group.media_player

automation:
  name: Automation
  view: yes
  entities:
    - group.automation_override
    - group.scripts
    - group.scenes
