################################################################
## Group / Automation
################################################################

scripts:
  name: Scripts
  entities:
    - script.rebuild_customize
    - script.restart_ha

automation_override:
  name: Automation Override
  entities:
    - input_boolean.https_proxy
