# Test for a specific brightness level

- alias: Let There Be Light
  trigger:
    platform: template
    entity_id: light.living_room_lamp
    value_template: "{{ trigger.to_state.attributes.brightness == 255 }}"
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.light_is_max
    state: 'on'

# Test for brightness in a range

- alias: Let There Be More Light
  trigger:
    platform: template
    entity_id: light.living_room_lamp
    value_template: "{{ trigger.to_state.attributes.brightness >= 170 and trigger.to_state.attributes.brightness <= 255 }}"
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.light_is_high
    state: 'on'

# Test for brightness in a range (simple, but not sure it'll work)

- alias: Let There Be Even More Light
  trigger:
    platform: numeric_state
    entity_id: light.living_room_lamp
    above: 0
    below: 85
    value_template: "{{ trigger.to_state.attributes.brightness }}"
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.light_is_low
    state: 'on'
