#################################################################
## Camera / HiTech
#################################################################

- platform: generic
  name: hitech_driveway
  still_image_url: !env_var CAMERA_HITECH_DRIVEWAY_URL

- platform: generic
  name: hitech_front_yard
  still_image_url: !env_var CAMERA_HITECH_FRONT_YARD_URL

- platform: generic
  name: hitech_barn
  still_image_url: !env_var CAMERA_HITECH_BARN_URL

- platform: generic
  name: hitech_camper
  still_image_url: !env_var CAMERA_HITECH_CAMPER_URL
