################################################################
## Sensor / SmartThings
################################################################

################################################
## Pepper Fan
################################################

- platform: mqtt
  name: pepper_fan_power
  state_topic: smartthings/pepper_fan/power
  unit_of_measurement: 'W'

################################################
## Garage Entry
################################################

- platform: mqtt
  name: garage_entry_battery
  state_topic: smartthings/garage_entry/battery
  unit_of_measurement: '%'

- platform: mqtt
  name: garage_entry_temperature
  state_topic: smartthings/garage_entry/temperature
  unit_of_measurement: '°F'

# - platform: mqtt
#   name: garage_entry_position
#   state_topic: smartthings/garage_entry/threeAxis

################################################
## Closet Door
################################################

- platform: mqtt
  name: closet_door_battery
  state_topic: smartthings/closet_door/battery
  unit_of_measurement: '%'

- platform: mqtt
  name: closet_door_temperature
  state_topic: smartthings/closet_door/temperature
  unit_of_measurement: '°F'

# - platform: mqtt
#   name: closet_door_position
#   state_topic: smartthings/closet_door/threeAxis

################################################
## Parker's Closet Door
################################################

- platform: mqtt
  name: parkers_closet_door_battery
  state_topic: smartthings/parkers_closet_door/battery
  unit_of_measurement: '%'

- platform: mqtt
  name: parkers_closet_door_temperature
  state_topic: smartthings/parkers_closet_door/temperature
  unit_of_measurement: '°F'

################################################
## Master Bedroom Motion Sensor
################################################

- platform: mqtt
  name: master_bedroom_battery
  state_topic: smartthings/master_bedroom_motion/battery
  unit_of_measurement: '%'

- platform: mqtt
  name: master_bedroom_motion_temperature
  state_topic: smartthings/master_bedroom_motion/temperature
  unit_of_measurement: '°F'

################################################
## Iris Smart Button
################################################

- platform: mqtt
  name: network_cabinet_battery
  state_topic: smartthings/network_cabinet/battery
  unit_of_measurement: '%'

- platform: mqtt
  name: network_cabinet_temperature
  state_topic: smartthings/network_cabinet/temperature
  unit_of_measurement: '°F'
