################################################################
## Automation / Home Assistant Startup
################################################################

################################################
## Startup Notification
################################################

- alias: Startup Notification
  trigger:
    platform: event
    event_type: homeassistant_start
  action:
    service: notify.telegram
    data:
      title: ''
      message: Home Assistant is now up and running.

################################################
## Rebuild Customize on Startup
################################################

# - alias: Rebuild Customize on Startup
#   trigger:
#     platform: event
#     event_type: homeassistant_start
#   action:
#     - delay: '00:01:00'
#     - service: shell_command.rebuild_customize
