################################################################
## Automation / Bathroom Lighting
################################################################

- alias: Master Bathroom Light ON when Motion Active
  trigger:
    platform: state
    entity_id: binary_sensor.master_bathroom_sensor_4
    to: 'on'
  condition:
    condition: state
    entity_id: switch.master_bathroom_motion
    state: 'on'
  action:
    service: light.turn_on
    entity_id: light.master_bathroom_1, light.master_bathroom_2
    data_template:
      brightness: "{{ states('sensor.time_brightness')|int }}"

- alias: Master Bathroom Light OFF when Motion Inactive
  trigger:
    platform: state
    entity_id: binary_sensor.master_bathroom_sensor_4
    to: 'off'
  condition:
    condition: state
    entity_id: switch.master_bathroom_motion
    state: 'on'
  action:
    service: light.turn_off
    entity_id: light.master_bathroom_1, light.master_bathroom_2
