################################################################
## Automation / Closet Lighting
################################################################

################################################
## Master Closet
################################################

- alias: Master Closet Light ON when Door is OPEN
  trigger:
    platform: state
    entity_id: binary_sensor.closet_door_contact
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.master_closet
    data_template:
      brightness: "{{ states('sensor.time_brightness')|int }}"

- alias: Master Closet Light OFF when Door is CLOSED
  trigger:
    platform: state
    entity_id: binary_sensor.closet_door_contact
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.master_closet

################################################
## Parker's Closet
################################################

- alias: "Parker's Closet Light ON when Door is OPEN"
  trigger:
    platform: state
    entity_id: binary_sensor.parkers_closet_door_contact
    to: 'on'
  action:
    service: light.turn_on
    entity_id: light.parkers_closet
    data_template:
      brightness: "{{ states('sensor.time_brightness')|int }}"

- alias: "Parker's Closet Light OFF when Door is CLOSED"
  trigger:
    platform: state
    entity_id: binary_sensor.parkers_closet_door_contact
    to: 'off'
  action:
    service: light.turn_off
    entity_id: light.parkers_closet

