################################################################
## Device Tracker
################################################################

################################################
## AsusWRT
################################################

- platform: asuswrt
  host: !env_var ASUSWRT_HOST
  protocol: ssh
  mode: router
  username: !env_var ASUSWRT_USERNAME
  ssh_key: !env_var ASUSWRT_SSH_KEY

################################################
## Bluetooth
################################################

- platform: bluetooth_tracker

################################################
## iCloud
################################################

# - platform: icloud
#   username: !env_var ICLOUD_USERNAME
#   password: !env_var ICLOUD_PASSWORD

################################################
## OwnTracks
################################################

# - platform: owntracks
#   max_gps_accuracy: 200
