input_select:
  tv_input:
    name: TV
    options:
      - 'OFF'
      - 'PS3'
    initial: 'OFF'

automation:
  - alias: PS3 input
    trigger:
      platform: state
      entity_id: input_select.tv_input
      to: 'PS3'
    action:
      - service: hdmi_cec.select_device
        data:
        device: PS3
      - service: persistent_notification.create
        data:
          message: 'PS3 ON'
          title: 'automation executed'

  - alias: Turn off TV
    trigger:
      platform: state
      entity_id: input_select.tv_input
      to: 'OFF'
    action:
      - service: hdmi_cec.standby
      - service: persistent_notification.create
        data:
          message: 'PS3 ON'
          title: 'automation executed'
